CREATE TABLE tabela(
    idcliente VARCHAR(20) PRIMARY KEY,
    genero VARCHAR(10),
    idoso INTEGER, 
    parceiro VARCHAR(3), 
    dependente VARCHAR(3), 
    tempo_casa INTEGER, 
    servico_telefone VARCHAR(3),
    multiplas_linhas VARCHAR(20),
    servico_internet VARCHAR(20),
    seguranca_online VARCHAR(20),
    backup VARCHAR(20),
    protecao_dispositivo VARCHAR(20),
    suporte_tecnico VARCHAR(20),
    streaming_tv VARCHAR(20),
    streaming_filmes VARCHAR(20),
    tipo_contrato VARCHAR(20),
    fatura_digital VARCHAR(3),
    metodo_pagamento VARCHAR(50),
    valor_mensal NUMERIC(10, 2),
    total_gasto VARCHAR(20),
    churn VARCHAR(3) 
);